- platform: mqtt
  name: "Driveway Light"
  state_topic: "smartthings/Driveway Light/switch"
  command_topic: "smartthings/Driveway Light/switch"
  payload_on: "on"
  payload_off: "off"
  retain: true
- platform: mqtt
  name: "Side Door Light"
  state_topic: "smartthings/Side Door Light/switch"
  command_topic: "smartthings/Side Door Light/switch"
  payload_on: "on"
  payload_off: "off"
  retain: true
- platform: mqtt
  name: "Front Porch Left"
  state_topic: "smartthings/Porch Left/switch"
  command_topic: "smartthings/Porch Left/switch"
  payload_on: "on"
  payload_off: "off"
  retain: true
- platform: mqtt
  name: "Front Porch Right"
  state_topic: "smartthings/Porch Right/switch"
  command_topic: "smartthings/Porch Right/switch"
  payload_on: "on"
  payload_off: "off"
  retain: true