- platform: mqtt
  name: "Upstairs Light"
  state_topic: "smartthings/Upstairs Light/switch"
  command_topic: "smartthings/Upstairs Light/switch"
  payload_on: "on"
  payload_off: "off"
  retain: true
- platform: mqtt
  name: "Main Theater"
  state_topic: "smartthings/Theater AV/switch"
  command_topic: "smartthings/Teather AV/switch"
  payload_on: "on"
  payload_off: "off"
  retain: true
