###############################################################################
#   @author         :   Jeffrey Stone 
#   @date           :   07/09/2019
#   @package        :   Jarvis
#   @description    :   Brining some Jarvis to Home Assistant
###############################################################################

automation:


script:
  activate_house_party_protocol:
    sequence:
    - service: scene.turn_on
      entity_id: scene.house_party_protocol
    - service: script.ah_report
      data_template:
        speech_message: >
          {{ [
          "Anchorage House has been configured for a House Party.",
          "Incense has been turned on.",
          "I have enabled house party protocol."
          ] | random }}