homeassistant:
  name: Home
  latitude: !secret MY_LATITUDE
  longitude: !secret MY_LONGITUDE
  elevation: 315
  unit_system: imperial
  time_zone: America/New_York
  customize: !include customize.yaml
group: !include groups.yaml
automation: !include automation.yaml
sensor: !include_dir_merge_list sensors
light: !include_dir_merge_list lights
switch: !include_dir_merge_list switches
script: !include scripts.yaml
alexa: !include alexa/intents.yaml
input_select: !include input_select.yaml
scene: !include scenes.yaml

http:
  api_password: !secret MY_API_PASS
  ssl_certificate: !secret SSL_CERT
  ssl_key: !secret SSL_KEY

zone:
  name: Home
  latitude: !secret MY_LATITUDE
  longitude: !secret MY_LONGITUDE
  radius: 100
  icon: mdi:account-multiple

mqtt:
 broker: 192.168.1.10
 port: 8883
 username: !secret MQTT_USER
 password: !secret MQTT_PASS

# View all events in a logbook
logbook:

# Enables support for tracking state changes over time.
history:

# Enables the frontend
frontend:

# Allows you to issue voice commands from the frontend
conversation:

#camera:
#  platform: mjpeg
#  mjpeg_url: !secret CAMERA
#  name: Skylars Room

climate:
  platform: honeywell
  username: !secret HONEYWELL_USER
  password: !secret HONEYWELL_PASS
  name: First Floor
  region: us

device_tracker:
  - platform: asuswrt
    host: 192.168.1.1
    protocol: telnet
    mode: router
    username: !secret ROUTER_USER
    password: !secret ROUTER_PASS
    track_new_devices: yes
    interval_seconds: 60
    consider_home: 180
  - platform: icloud
    username: !secret ICLOUD_USER
    password: !secret ICLOUD_PASS
    interval_seconds: 60
    consider_home: 180


notify:
#  platform: googlevoice
#  username: !secret GV_USER
#  password: !secret GV_PASS
#  name: googlevoice
  platform: pushbullet
  api_key: !secret pushbullet_api

ifttt:
  key: !secret IFTTT_API_KEY

media_player:
  platform: cast
  host: 192.168.1.219

garage_door:
  platform: mqtt
  name: 'Garage Door'
  state_topic: 'smartthings/Garage Door/contact'
  command_topic: 'smartthings/Garage Door/door'
  state_open: 'open'
  state_closed: 'closed'
  service_open: 'open'
  service_close: 'closed'
  retain: true
  optimistic: true

# Discover some devices automatically
discovery:

# Checks for available updates
updater:

# Track the sun
sun:
