homeassistant:
  name: Home
  latitude: !secret MY_LATITUDE
  longitude: !secret MY_LONGITUDE
  elevation: 315
  unit_system: imperial
  time_zone: America/New_York
  customize: !include customize.yaml
  auth_providers:
    - type: homeassistant
  packages: !include_dir_named packages

default_config:

ssdp:

zeroconf:

system_health:

mobile_app:

person:

frontend:
  themes: !include_dir_merge_named themes
  javascript_version: latest

http:
  #api_password: !secret MY_API_PASS
  #ssl_certificate: !secret SSL_CERT
  #ssl_key: !secret SSL_KEY
  #base_url: !secret BASEURL
  ssl_certificate: !secret ahsl_ssl_cert
  ssl_key: !secret ahsl_ssl_key
  base_url: !secret ahsl_base_url
  use_x_forwarded_for: True
  trusted_proxies:
    - 127.0.0.1
    - ::1
  ip_ban_enabled: True
  login_attempts_threshold: 3

config:

cloud:
  

wemo:
  discovery: true



weather:
  - platform: darksky
    api_key: !secret darksky_api
    name: Grayson

conversation:

device_tracker:
  # - platform: icloud
  #   username: !secret ICLOUD_USER
  #   password: !secret ICLOUD_PASS
  #   track_new_devices: yes
  # - platform: owntracks
  # 
  # - platform: eero_tracker
  #   consider_home: 300
  #   interval_seconds: 60
  #   track_new_devices: yes
  #   only_macs: "d0:c5:f3:80:50:5e, f4:31:c3:84:1d:d1, 08:74:02:CC:C4:97, 5C:F5:DA:9B:5A:A2, 34:7C:25:CC:9D:0F, 64:52:99:93:F1:B3"


google:
  client_id: !secret google_client_id
  client_secret: !secret google_client_secret

arlo:
  username: !secret arlo_user
  password: !secret arlo_pass

alarm_control_panel:
  - platform: arlo
    home_mode_name: home
    away_mode_name: armed

discovery:
  ignore:
    - igd

updater:
  include_used_components: true

sun:

recorder:
  #db_url: sqlite:///data/home-assistant_v2.db
  purge_keep_days: 2
  exclude:
    domains:
      - automation
      - weblink
      - updater
    entities:
      - sun.sun # Don't record sun data
      - sensor.last_boot # Comes from 'systemmonitor' sensor platform
      - sensor.date


logbook:
  include:
    domains:
      - media_player
      - automation
      - script

logger:
  default: warning
  #logs:
 
  #   homeassistant.components.sensor.alpha_vantage: debug


history:
  include:
    domains:
      - sensor
      - switch
      - media_player
      - light

cast:

# speedtestdotnet:
 
mqtt:
  broker: 192.168.7.67
  port: 1883
  username: !secret MQTT_USER
  password: !secret MQTT_PASS
  discovery: true
  birth_message:
    topic: 'hass/status'
    payload: 'online'
  will_message:
    topic: 'hass/status'
    payload: 'offline'

camera:
  - platform: mjpeg
    name: Garage Door Cam 
    mjpeg_url: !secret garage_cam
  - platform: arlo
    ffmpeg_arguments: '-pred 1 -q:v 2'

media_player:
  - platform: vlc
    name: hass_speaker
    arguments: '--alsa-audio-device=hw:1,0'
    
ffmpeg:
  ffmpeg_bin: /usr/bin/ffmpeg    

##splunk:
# host: 192.168.7.40
# token: !secret splunkit
# port: 8088

cloudflare:
  email: !secret cloudflare_user
  api_key: !secret cloudflare_api
  zone: !secret cloudflare_zone
  records:
    - ah

life360:
  accounts:
    - username: !secret life360_username
      password: !secret life360_password

media_extractor:

### Includes ###
alert: !include_dir_merge_named alerts/
group: !include groups.yaml
automation: !include automations.yaml
sensor: !include_dir_merge_list sensors
binary_sensor: !include_dir_merge_list binary_sensors
light: !include_dir_merge_list lights
switch: !include_dir_merge_list switches
script: !include_dir_merge_named scripts
intent_script: !include intents/intents.yaml
scene: !include scenes.yaml
input_select: !include input_select.yaml
input_boolean: !include input_boolean.yaml
input_datetime: !include input_datetime.yaml
zone: !include zones.yaml

python_script:

#duckdns:
#  domain: !secret duckdns_domain
#  access_token: !secret duckdns_token

### Services

# Disabled due to bug that causes too many open files - Need to track it down
# cover:
#   platform: myq
#   username: !secret myq_user
#   password: !secret myq_pass
#   type: chamberlain

ecobee:
  api_key: !secret ecobee_api

map:

wwlln:
  radius: 75
  latitude: !secret MY_LATITUDE
  longitude: !secret MY_LONGITUDE

tplink:
  discovery: false
  switch:
    - host: 192.168.7.105
    - host: 192.168.7.107
    
# zwave:
#   usb_path: /dev/ttyACM0
#   network_key: !secret zwave_key

#googlehome:
#  devices:
#    - host: 192.168.7.97

ifttt:
  key: !secret IFTTT_API_KEY

### Custom Commands
shell_command:
  alarm_off: pkill mpg123
  vlc_off: pkill vlc
  tornado_alarm: mpg123 /media/audio/Tornado_Siren.mp3
  door_chime: mpg123 /media/audio/Store_Door_Chime.mp3
  security_alarm: mpg123 /media/audio/security_siren.mp3
  security_alarm_intro: mpg123 /media/audio/Siren_Noise.mp3
  welcome_haunted: mpg123 /media/audio/Welcome-Hunted.mp3
  haunted_guest_welcome: mpg123 /media/audio/haunted_guest_welcome.mp3
  haunted_mansion_preshow_full: cvlc --play-and-exit /media/audio/haunted_mansion_preshow_full.mp3
  haunted_mansion_preshow_short: mpg123 /media/audio/haunted_mansion_preshow_short.mp3
  haunted_mansion_hurry_back_short: mpg123 /media/audio/haunted_mansion_hurry_back_short.mp3
  haunted_mansion_hurry_back_full: mpg123 /media/audio/haunted_mansion_hurry_back_full.mp3
  happily_ever_after: cvlc --play-and-exit /media/audio/Happily_Ever_After_Audio.mp3
  boo_to_you: cvlc --play-and-exit /media/audio/boo_to_you_audio.mp3
  haunted_mansion_ride: cvlc --play-and-exit /media/audio/haunted_mansion_ride.mp3
  holiday_wishes_preshow: mpg123 /media/audio/wishes_5_min.mp3
  holiday_wishes: cvlc --play-and-exit /media/audio/holidaywishes.mp3
  disney_springs_xmas: cvlc --play-and-exit /media/audio/disney_springs_xmas.mp3
  american_adventure: cvlc --play-and-exit /media/audio/The_American_Adventure.mp3
  welcome_show: cvlc --play-and-exit /media/audio/welcome_show.mp3
  monorail_waiting: mpg123 /media/audio/monorail_waiting.mp3
  monorail_mk: mpg123 /media/audio/monorail.mp3
  monorail_resort: mpg123 /media/audio/monorail_resort.mp3
  welcome_to_mk: cvlc --play-and-exit /media/audio/welcome_magic_kingdom.mp3
  welcome_show_crowd: cvlc --play-and-exit /media/audio/welcome_show_crowd.mp3
  spaceship_earth_ride: cvlc --play-and-exit /media/audio/spaceship_earth_ride.mp3
  this_is_halloween: cvlc --play-and-exit /media/audio/This_is_Halloween.mp3
  sleepy_hollow_audiobook: cvlc --play-and-exit /media/audio/the_legend_of_sleepy_hollow_read_along.mp3
  dance_it: cvlc --play-and-exit /media/audio/move_it_shake_dance_audio.mp3
  hass_vol_up: sudo amixer set PCM -- $[$(amixer get PCM|grep -o [0-9]*%|sed 's/%//')+5]%
  hass_vol_dn: sudo amixer set PCM -- $[$(amixer get PCM|grep -o [0-9]*%|sed 's/%//')-5]%
  normal_vol: amixer -c 0 set PCM 93%
  tiki_vol: amixer -c 0 set PCM 95% 
  full_vol: amixer -c 0 set PCM 100%
  reset_alexa_cookie: /home/homeassistant/bin/resetalexacookie
  tiki_room_audio: cvlc --play-and-exit /media/audio/tiki_room_audio.mp3
  illuminations_audio: cvlc --play-and-exit /media/audio/illuminations.mp3
  mk_audio: cvlc --play-and-exit /media/audio/magic_kingdom.mp3
  usps: python /home/homeassistant/bin/usps.py 
  backup: python /home/homeassistant/bin/dropbox.py

  # haunted noises

  haunted_scream: mpg123 /media/audio/haunted/Scream.mp3
  haunted_raven: mpg123 /media/audio/haunted/RavenSound.mp3
  haunted_door: mpg123 /media/audio/haunted/OldDoorCreaking.mp3
  haunted_howling: mpg123 /media/audio/haunted/Howling.mp3
  haunted_seance_horn: mpg123 /media/audio/haunted/Haunted_Mansion_Seance_Horn.mp3
  haunted_piano: mpg123 /media/audio/haunted/Haunted_Mansion_Piano.mp3
  haunted_leotta: mpg123 /media/audio/haunted/Haunted_Mansion_Leotta.mp3
  haunted_harp: mpg123 /media/audio/haunted/Haunted_Mansion_Harp.mp3
  haunted_clock: mpg123 /media/audio/haunted/Haunted_Mansion_Clock.mp3
  haunted_ballroom: mpg123 /media/audio/haunted/Haunted_Mansion_Ballroom.mp3
  haunted_bells: mpg123 /media/audio/haunted/Jaunted_Bells-Chimming.mp3
  haunted_laugh: mpg123 /media/audio/haunted/Evil_Laugh.mp3
  haunted_door2: mpg123 /media/audio/haunted/CreakingDoorSpooky.mp3
  haunted_chains: mpg123 /media/audio/haunted/ChainsRattling.mp3
  haunted_laugh2: mpg123 /media/audio/haunted/BigLaugh.mp3