homeassistant:
  name: Home
  latitude: !secret MY_LATITUDE
  longitude: !secret MY_LONGITUDE
  elevation: 315
  unit_system: imperial
  time_zone: America/New_York
  customize: !include customize.yaml

frontend:
  themes:
    blue:
      primary-color: "#356AA0"

http:
  api_password: !secret MY_API_PASS
  #ssl_certificate: !secret SSL_CERT
  #ssl_key: !secret SSL_KEY
  #base_url: !secret BASEURL
  cors_allowed_origins:
    - https://google.com
    - https://home-assistant.io
  use_x_forwarded_for: True
  trusted_networks:
    - 127.0.0.1
  ip_ban_enabled: True
  login_attempts_threshold: 5

config:

cloud:
  alexa:
    filter:
      include_entities:
      - sensor.accurite_back_porch_temperature
      - sensor.accurite_garage_temperature
      - sensor.kat_location
      - sensor.jeff_location
      - sensor.jeff_ett_home
      - sensor.kat_ett_home
      include_domains:
      - switch
      - light
      - cover
      - scene
      - script
      - input_boolean
      exclude_domains:
      - group
      - alert
      - automation
    entity_config:
      sensor.accurite_back_porch_temperature:
        name: Back Porch
        description: Back Porch Temperature
      sensor.accurite_garage_temperature:
        name: Garage
        description: Garage Temperature
      sensor.kat_location:
        name: Kats Location
        description: Kats Location
      sensor.jeff_location:
        name: Jeffs Location
        description: Jeffs Location
      sensor.jeff_ett_home:
        name: Jeffs Arrival
        description: Jeffs arrival in minutes
      sensor.kat_ett_home:
        name: Kats Arrival
        description: Katss arrival in minutes

alexa:

conversation:

device_tracker:
  - platform: icloud
    username: !secret ICLOUD_USER
    password: !secret ICLOUD_PASS
    track_new_devices: yes
  - platform: eero_tracker
    consider_home: 300
    interval_seconds: 60 # Recommended...do not set this lower than 25, we don't want to DDOS Eero
  
discovery:

updater:

sun:

recorder:
  purge_keep_days: 5
  exclude:
    domains:
      - automation
      - weblink
      - updater
    entities:
      - sun.sun 
      - sensor.last_boot 
      - sensor.date

logger:
  default: warn

history:

cast:
  
media_player:
  - platform: apple_tv
    host: 192.168.7.58
    login_id: !secret apple_tv_login
    credentials: !secret apple_cred
  - platform: roku
    host: 192.168.7.52
    name: roku living room
  - platform: yamaha
    host: 192.168.7.56
    source_ignore:
      - "AUX"
      - "V-AUX"
      - "AV1"
      - "AV2"
      - "AV3"
      - "AV4"
      - "AV5"
      - "AV6"
      - "SiriusXM"
      - "Pandora"
      - "Rhapsody"
      - "TURNER"
      - "AUDIO1"
      - "AUDIO2"
      - "SERVER"
    source_names:
      HDMI1: "BluRay"
      HDMI2: "Chromecast"
      HDMI3: "Xbox"
      HDMI4: "Roku"
      HDMI5: "AppleTv"
    zone_ignore:
      - "Zone_2"
    zone_names:
      Main_Zone: "Theater"


tts:
  - platform: google
    cache: true
    cache_dir: /tmp/tts
    time_memory: 300

notify:
  - platform: ios
  - name: all_ios
    platform: group
    services:
      - service: ios_jeffreystonesiphone
      - service: ios_jeffreystonesipad
      - service: ios_katherinestonesiphone
  - name: jeff_ios
    platform: group
    services:
      - service: ios_jeffreystonesiphone
      - service: ios_jeffreystonesipad
 
mqtt:
 broker: !secret MQTT_HOST
 port: 1883
 username: !secret MQTT_USER
 password: !secret MQTT_PASS


### Includes ###
alert: !include_dir_merge_named alerts/
group: !include groups.yaml
automation: !include_dir_merge_list automations/
sensor: !include_dir_merge_list sensors
binary_sensor: !include_dir_merge_list binary_sensors
light: !include_dir_merge_list lights
switch: !include_dir_merge_list switches
script: !include_dir_merge_named scripts/
intent_script: !include intents/intents.yaml
scene: !include scenes.yaml
input_select: !include input_select.yaml
input_boolean: !include input_boolean.yaml
zone: !include zones.yaml

### Devices and Services

cover:
  - platform: mqtt
    name: "Garage Door"
    state_topic: 'smartthings/Garage Door/contact'
    command_topic: 'smartthings/Garage Door/door'
    state_open: 'open'
    state_closed: 'closed'
    payload_open: 'open'
    payload_close: 'closed'
    retain: true
    optimistic: true

climate:
  platform: honeywell
  username: !secret HONEYWELL_USER
  password: !secret HONEYWELL_PASS
  name: First Floor
  region: us
  scan_interval: 600

map:
  
### Custom Commands

shell_command:
  alarm_off: pkill mpg123
  tornado_alarm: mpg123 /media/audio/Tornado_Siren.mp3
  door_chime: mpg123 /media/audio/Store_Door_Chime.mp3
  security_alarm: mpg123 /media/audio/security_siren.mp3
  security_alarm_intro: mpg123 /media/audio/Siren_Noise.mp3
