title: Anchorage House
views:
  - icon: mdi:home-assistant
    # View tab title.
    title: Home
    # Unique id for direct access /lovelace/${id}. If you don't specify one, it is added automatically.
    id: home
    theme: midnight-AH
    # The cards to show on this view.
    cards:
        # The filter card will filter entities for their state
      - id: anchoragehouse # Every card needs an ID, if you don't specify one, it is added automatically.
        type: glance
        title: Anchorage House
        entities:
          - entity: sensor.family_status
            name:
          - entity: input_boolean.guest_mode
            name:
          - entity: input_boolean.vacation_mode
            name:
          - entity: sensor.jeff_location
            name:
          - entity: sensor.kat_location
            name: 
          
      - type: entities
        title: Downstairs
        entities:
          - switch.fireplace_lights
          - light.tower_lamp
          - light.front_lamp
          - switch.incense
          - light.kitchen_cabinets
          - light.kitchen_light_strip
          - switch.master_bedroom_fan

      - type: entities
        title: Upstairs
        entities:
          - switch.upstairs_light
          - light.upstairs_lamp

      - type: entities
        title: Outdoors
        entities:
          - switch.front_porch
          - switch.driveway_light
          - switch.side_door

      - type: entities
        title: Holiday
        entities:
          - entity: switch.christmas_tree
            name: Christmas Tree
            icon: mdi:pine-tree
          - entity: switch.upstairs_christmas_tree
            name: Upstairs Christmas Tree
            icon: mdi:pine-tree

      - type: vertical-stack
        cards:
          - id: weatheralerts 
            type: entity-filter
            entities:
              - sensor.storm_statement
              - sensor.tstorm_watch
              - sensor.tstorm_warning
              - sensor.tornado_watch
              - sensor.tornado_warning
            state_filter:
              - 'active'
            card:
              type: glance
              title: 
          - type: weather-forecast
            entity: weather.grayson
          - type: glance
            title:
            entities:
              - entity: sensor.accurite_back_porch_temperature
                name: Back Temp
              - entity: sensor.accurite_back_porch_humidity
                name: Back Humidity
              - sensor.accurite_garage_temperature
              - sensor.accurite_garage_humidity
          - type: thermostat
            entity: climate.first_floor

      - type: entities
        entities:
          - entity: media_player.yamaha_receiver_theater
          - entity: media_player.living_room_tv
            name: Theater Chromecast
          - entity: media_player.roku_5s6719003683
            name: Master Bedroom Roku
          - entity: media_player.guest_tv
            name: Master Bedroom Chromecast
          - entity: media_player.googlehome7470
            name: Theater Google Home

      - type: vertical-stack
        cards:
          - id: spotifyplayer
            type: entities
            entities:
              - entity: media_player.spotify
                name: Spotify
              - input_select.spotify_source
              - input_boolean.shuffle_spotify
          - type: horizontal-stack
            cards:
            - id: skylarxmas
              type: entity-button
              tap_action: 
                action: call-service
                  service: script.turn_on
                  service_data:
                    entity: script.play_skylars_christmas_playlist
              
              icon: mdi:music
              name: Skylar's Christmas
            - id: greenplaylist
              type: entity-button
              tap_action:
                action: call-service
                  service: script.turn_on
                  service_data:
                    entity: script.play_skylars_playlist
              icon: mdi:music
              name: Skylar's Playlist

      - type: vertical-stack
        cards:
          - id: doorsalerts 
            type: entity-filter
            entities:
              - binary_sensor.back_door
              - binary_sensor.front_door
              - binary_sensor.laundry_room_door
              - binary_sensor.attic_door
              - binary_sensor.side_door
              - binary_sensor.garage_door
              - binary_sensor.garage_dome_sensor
            state_filter:
              - 'on'
            card:
              type: glance
              title: 

  - icon: mdi:weather-sunny
    title: Weather Details
    cards:
      - type: iframe
        url: https://embed.windy.com/embed2.html?lat=33.895&lon=-84.012&zoom=12&level=surface&overlay=radar&menu=&message=&marker=&calendar=&pressure=&type=map&location=coordinates&detail=&detailLat=33.895&detailLon=-84.012&metricWind=default&metricTemp=default&radarRange=-1
        aspect_ratio: 100%

  - icon: mdi:settings
    title: Settings
    cards:
      - type: entities
        title: Notifications
        entities:
          - input_boolean.audible_notifications
          - input_boolean.text_notifications
          - input_boolean.text_notify_jeff
          - input_boolean.text_notify_kat
          - input_boolean.presence_audio_notifications
          - input_boolean.presence_text_notifications
          
      - type: entities
        title: Alarms
        entities:
          - input_boolean.skylar_dressed_alarm
          - input_select.trash_pickup
          - input_select.recycle_pickup
          - input_boolean.trash_notification

        # The markdown card will render markdown text.
      - type: markdown
        title: Lovelace
        content: >
          Welcome to your **Lovelace UI**

  - icon: mdi:home-automation
    title: Home Automation
    cards:
      - type: entities
        title: System 
        entities:
          - sensor.cpu
          - sensor.disk_use_percent_
          - sensor.memory_use_percent
          - sensor.network_in_eth0
          - sensor.network_out_eth0
          - sensor.last_boot
          - sensor.ha_uptime
          - sensor.lets_encrypt_expiration
          - sensor.installed_version
          - sensor.current_ha_version
          - sensor.ha_v2db
          - sensor.ha_log
          
      - type: entities
        title: Network Speed
        entities:
          - sensor.speedtest_ping
          - sensor.speedtest_download
          - sensor.speedtest_upload

  
  - icon: mdi:human-male-female
    title: People
    cards:
      - type: entities
        title: Jeff
        show_header_toggle: false 
        entities:
          - sensor.jeff_location
          - sensor.jeff_destination
          - sensor.jeff_iphone_batt
          - device_tracker.jeffreysapple_watch
          - device_tracker.jstonemac
          - device_tracker.jeffreystonesipad
          - sensor.jeff_ett_home
          - input_boolean.jeff_travel_monitor
          - input_boolean.text_notify_jeff
          - input_boolean.jeff_traffic_alerts
      
      - type: entities
        title: Kat
        show_header_toggle: false
        entities:
          - sensor.kat_location
          - sensor.kat_destination
          - sensor.kat_iphone_batt
          - device_tracker.katherinesmini
          - device_tracker.katherinesipad
          - sensor.kat_ett_home
          - input_boolean.kat_travel_monitor
          - input_boolean.text_notify_kat
