- platform: template
  sensors:
    jeff_iphone_batt:
      unit_of_measurement: '%'
      value_template: >-
          {%- if states.device_tracker.jeffreystonesiphone.attributes.battery %}
              {{ states.device_tracker.jeffreystonesiphone.attributes.battery | round(1) }}
          {% else %}
              {{ states.sensor.jeff_iphone_batt.state }}
          {%- endif %}
      icon_template: '{%- if is_state("sensor.jeff_iphone_batt", "unknown") %}mdi:battery-unknown{%- elif is_state_attr("device_tracker.jeffreystonesiphone", "battery_status", "Charging") %}mdi:battery-charging{%- elif  states.device_tracker.jeffreystonesiphone.attributes.battery <= 5 %}mdi:battery-outline{%- elif states.device_tracker.jeffreystonesiphone.attributes.battery >= 95 %}mdi:battery{% else %}mdi:battery-{{(states.device_tracker.jeffreystonesiphone.attributes.battery|float / 10)|round*10}}{%- endif %}'
    kat_iphone_batt:
      unit_of_measurement: '%'
      value_template: >-
          {%- if states.device_tracker.katherinestonesiphone.attributes.battery %}
              {{ states.device_tracker.katherinestonesiphone.attributes.battery | round(1) }}
          {% else %}
              {{ states.sensor.kat_iphone_batt.state }}
          {%- endif %}
      icon_template: '{%- if is_state("sensor.kat_iphone_batt", "unknown") %}mdi:battery-unknown{%- elif is_state_attr("device_tracker.katherinestonesiphone", "battery_status", "Charging") %}mdi:battery-charging{%- elif  states.device_tracker.katherinestonesiphone.attributes.battery <= 5 %}mdi:battery-outline{%- elif states.device_tracker.katherinestonesiphone.attributes.battery >= 95 %}mdi:battery{% else %}mdi:battery-{{(states.device_tracker.katherinestonesiphone.attributes.battery|float / 10)|round*10}}{%- endif %}'
- platform: mqtt
  name: "Front Door Battery"
  state_topic: "zwave2mqtt/nodeID_27/128/1/0"
- platform: mqtt
  name: "Laundry Door Battery"
  state_topic: "zwave2mqtt/nodeID_26/128/1/0"
- platform: mqtt
  name: "Kitchen Smoke Battery"
  state_topic: "zwave2mqtt/nodeID_19/128/1/0"
- platform: mqtt
  name: "Attic Door Battery"
  state_topic: "zwave2mqtt/nodeID_18/128/1/0"
- platform: mqtt
  name: "Washer Door Battery"
  state_topic: "zwave2mqtt/washer_door/128/1/0"
- platform: mqtt
  name: "Back Door Battery"
  state_topic: "zwave2mqtt/nodeID_28/128/1/0"
- platform: mqtt
  name: "Side Door Battery"
  state_topic: "zwave2mqtt/side_door/128/1/0"
- platform: mqtt
  name: "Garage Door Battery"
  state_topic: "zwave2mqtt/nodeID_16/128/1/0"
- platform: mqtt 
  name: "Garage Motion Battery"
  state_topic: "zwave2mqtt/garage_motion/128/1/0"
- platform: mqtt
  name: "Dome Alarm"
  state_topic: "zwave2mqtt/nodeID_21/128/1/0"