- platform: mqtt
  name: "Front Door Battery"
  state_topic: "smartthings/Front Door/battery"
- platform: mqtt
  name: "Laundry Door Battery"
  state_topic: "smartthings/Laundry Room Door/battery"
- platform: mqtt
  name: "Kitchen Smoke Battery"
  state_topic: "smartthings/Kitchen Smoke/battery"
- platform: mqtt
  name: "Attic Door Battery"
  state_topic: "smartthings/Attic Door/battery"
- platform: mqtt
  name: "Washer Door Battery"
  state_topic: "smartthings/Washer Door/battery"
- platform: mqtt
  name: "Back Door Battery"
  state_topic: "smartthings/Back Door/battery"
- platform: template
  sensors:
    jeff_iphone_batt:
      unit_of_measurement: '%'
      value_template: >-
          {%- if states.device_tracker.jeffrey_377fadfe9d7e410fb71bd84c06547c00.attributes.battery %}
              {{ states.device_tracker.jeffrey_377fadfe9d7e410fb71bd84c06547c00.attributes.battery | round(1) }}
          {% else %}
              {{ states.sensor.jeff_iphone_batt.state }}
          {%- endif %}
      icon_template: '{%- if is_state("sensor.jeff_iphone_batt", "unknown") %}mdi:battery-unknown{%- elif is_state_attr("device_tracker.jeffreystonesiphone", "battery_status", "Charging") %}mdi:battery-charging{%- elif  states.device_tracker.jeffreystonesiphone.attributes.battery <= 5 %}mdi:battery-outline{%- elif states.device_tracker.jeffreystonesiphone.attributes.battery >= 95 %}mdi:battery{% else %}mdi:battery-{{(states.device_tracker.jeffreystonesiphone.attributes.battery|float / 10)|round*10}}{%- endif %}'
    kat_iphone_batt:
      unit_of_measurement: '%'
      value_template: >-
          {%- if states.device_tracker.kat_2f1c672110dd491ea7dca9833d1c6cf5.attributes.battery %}
              {{ states.device_tracker.kat_2f1c672110dd491ea7dca9833d1c6cf5.attributes.battery | round(1) }}
          {% else %}
              {{ states.sensor.kat_iphone_batt.state }}
          {%- endif %}
      icon_template: '{%- if is_state("sensor.kat_iphone_batt", "unknown") %}mdi:battery-unknown{%- elif is_state_attr("device_tracker.katherinestonesiphone", "battery_status", "Charging") %}mdi:battery-charging{%- elif  states.device_tracker.katherinestonesiphone.attributes.battery <= 5 %}mdi:battery-outline{%- elif states.device_tracker.katherinestonesiphone.attributes.battery >= 95 %}mdi:battery{% else %}mdi:battery-{{(states.device_tracker.katherinestonesiphone.attributes.battery|float / 10)|round*10}}{%- endif %}'
