- platform: template
  sensors:
      amazon_dot_lr:
        friendly_name: 'Amazon Dot LR'
        value_template: "{{ 'Online' if is_state('device_tracker.kindlecdf98981f', 'home') else 'Offline' }}"

      amazon_dot_kn:
        friendly_name: 'Amazon Dot KN'
        value_template: "{{ 'Online' if is_state('device_tracker.kindle23d7b37a0', 'home') else 'Offline' }}"

      circle:
        friendly_name: 'Disney Circle'
        value_template: "{{ 'Online' if is_state('device_tracker.circle', 'home') else 'Offline' }}"

      tycho:
        friendly_name: 'tycho'
        value_template: "{{ 'Online' if is_state('device_tracker.jarvis', 'home') else 'Offline' }}"

      tightbeam:
        friendly_name: 'tightbeam'
        value_template: "{{ 'Online' if is_state('device_tracker.tightbeam', 'home') else 'Offline' }}"

      appletv:
        friendly_name: 'Apple Tv'
        value_template: "{{ 'On' if is_state('media_player.apple_tv', 'on') else 'Off' }}"

      xboxone:
        friendly_name: 'xboxone'
        value_template: "{{ 'Online' if is_state('device_tracker.xboxone', 'home') else 'Offline' }}"

      chromecast:
        friendly_name: 'Chromecast'
        value_template: "{{ 'On' if is_state('media_player.chromecast_lr', 'on') else 'Off' }}"

      smartthings:
        friendly_name: 'SmartThings'
        value_template: "{{ 'Online' if is_state('device_tracker.d052a8170fef', 'home') else 'Offline' }}"

      samsungtv:
        friendly_name: 'Samsung Tv'
        value_template: "{{ 'On' if is_state('media_player.pn60e550_pn60e550', 'on') else 'Off' }}"

      honeywell:
        friendly_name: 'Honeywell'
        value_template: "{{ 'Online' if is_state('device_tracker.gateway2f3bca', 'home') else 'Offline' }}"

      router:
        friendly_name: 'Asus Router'
        value_template: "{{ 'Online' if is_state('device_tracker.routerasuscom', 'home') else 'Offline' }}"

      kat_mini:
        friendly_name: "Kat's Mini"
        value_template: "{{ 'Online' if is_state('device_tracker.katherinesmini', 'home') else 'Offline' }}"

      jeff_mbp:
        friendly_name: "Jeff's MBP"
        value_template: "{{ 'Online' if is_state('device_tracker.jeffreysmbp', 'home') else 'Offline' }}"

      jeff_work_mbp:
        friendly_name: "Jeff's Work MBP"
        value_template: "{{ 'Online' if is_state('device_tracker.jstonemac', 'home') else 'Offline' }}"

      jeff_ipad:
        friendly_name: "Jeff's iPad"
        value_template: "{{ 'Online' if is_state('device_tracker.jeffreystonesipad', 'home') else 'Offline' }}"

      kat_ipad:
        friendly_name: "Kat's iPad"
        value_template: "{{ 'Online' if is_state('device_tracker.katherinesipad', 'home') else 'Offline' }}"

      jeff_iphone_batt:
        unit_of_measurement: '%'
        value_template: >-
            {%- if states.device_tracker.jeffreystonesiphone.attributes.battery %}
                {{ states.device_tracker.jeffreystonesiphone.attributes.battery | round(1) }}
            {% else %}
                {{ states.sensor.jeff_iphone_batt.state }}
            {%- endif %}
        icon_template: '{%- if is_state("sensor.jeff_iphone_batt", "unknown") %}mdi:battery-unknown{%- elif is_state_attr("device_tracker.jeffreystonesiphone", "battery_status", "Charging") %}mdi:battery-charging{%- elif  states.device_tracker.jeffreystonesiphone.attributes.battery <= 5 %}mdi:battery-outline{%- elif states.device_tracker.jeffreystonesiphone.attributes.battery >= 95 %}mdi:battery{% else %}mdi:battery-{{(states.device_tracker.jeffreystonesiphone.attributes.battery|float / 10)|round*10}}{%- endif %}'

      kat_iphone_batt:
        unit_of_measurement: '%'
        value_template: >-
            {%- if states.device_tracker.katherinestonesiphone.attributes.battery %}
                {{ states.device_tracker.katherinestonesiphone.attributes.battery | round(1) }}
            {% else %}
                {{ states.sensor.kat_iphone_batt.state }}
            {%- endif %}
        icon_template: '{%- if is_state("sensor.kat_iphone_batt", "unknown") %}mdi:battery-unknown{%- elif is_state_attr("device_tracker.katherinesiphone", "battery_status", "Charging") %}mdi:battery-charging{%- elif  states.device_tracker.katherinesiphone.attributes.battery <= 5 %}mdi:battery-outline{%- elif states.device_tracker.katherinesiphone.attributes.battery >= 95 %}mdi:battery{% else %}mdi:battery-{{(states.device_tracker.katherinesiphone.attributes.battery|float / 10)|round*10}}{%- endif %}'
