- platform: google_travel_time
  name: "Jeff ETT Home"
  api_key: !secret google_api
  origin: device_tracker.owntracks_jeffreysphone
  destination: zone.home
- platform: google_travel_time
  name: "Kat ETT Home"
  api_key: !secret google_api
  origin: device_tracker.katheriesiphone_2
  destination: zone.home
