- platform: mqtt
  name: "Washer Status"
  state_topic: "house/washer/status"
- platform: history_stats
  name: Jeff Driving Time
  entity_id: sensor.jeff_driving
  state: 'on'
  type: time
  end: '{{ now() }}'
  duration:
    days: 7
- platform: history_stats
  name: Kat Driving Time
  entity_id: sensor.kat_driving
  state: 'on'
  type: time
  end: '{{ now() }}'
  duration:
    days: 7
- platform: history_stats
  name: Speech time
  entity_id: media_player.theater
  state: 'playing'
  type: time
  end: '{{ now() }}'
  duration:
    days: 7
- platform: history_stats
  name: AppleTV time
  entity_id: media_player.apple_tv
  state: 'playing'
  type: time
  end: '{{ now() }}'
  duration:
    hours: 24
- platform: history_stats
  name: Roku time
  entity_id: media_player.bedroom
  state: 'playing'
  type: time
  end: '{{ now() }}'
  duration:
    hours: 24
- platform: history_stats
  name: Washer Time
  entity_id: sensor.washer_status
  state: 'running'
  type: time
  end: '{{ now() }}'
  duration:
    days: 7
- platform: min_max
  name: Outside Temp Stats
  entity_ids:
  - sensor.accurite_back_porch_temperature
- platform: min_max
  name: Garage Temp Stats
  entity_ids:
  - sensor.accurite_garage_temperature
- platform: min_max
  name: Inside Temp Stats
  entity_ids:
  - sensor.craft_room_temperature
  - sensor.kitchen_temperature
  - sensor.living_room_temperature
  - sensor.master_bedroom_temperature
  - sensor.skylar_room_temperature
- platform: arlo
  monitored_conditions:
  - captured_today
  - last_capture
  - total_cameras
  - battery_level
  - signal_strength
- platform: template
  sensors:
    sensor_count:
      friendly_name: 'Number of Sensors'
      entity_id: []
      value_template: >-
        {{ states.sensor | list | count }}
    automation_count:
      friendly_name: 'Number of Automations'
      entity_id: []
      value_template: >-
        {{ states.automation| list | count }}
    script_count:
      friendly_name: 'Number of Scripts'
      entity_id: []
      value_template: >-
        {{ states.script | list | count }}
    binary_sensor_count:
      friendly_name: 'Number of Binary Sensors'
      entity_id: []
      value_template: >-
        {{ states.binary_sensor | list | count }}
    tracker_count:
      friendly_name: 'Number of Devices'
      entity_id: []
      value_template: >-
        {{ states.device_tracker| list | count }}
    lights_count:
      friendly_name: 'Number of Lights'
      entity_id: []
      value_template: >-
        {{ states.light | list | count }}
    camera_count:
      friendly_name: 'Number of online Cameras'
      entity_id: []
      value_template: >-
        {{ states.camera | list | count }}
