- platform: mqtt
   state_topic: "owntracks/owntracks/jeffreysphone"
   name: "Jeffs Phone Battery"
   unit_of_measurement: "%"
   value_template: '{{ value_json.batt }}'
- platform: mqtt
   state_topic: "owntracks/owntracks/jeffreysphone"
   name: "Jeffs Velocity"
   unit_of_measurement: "%"
   value_template: '{{ value_json.vel }}'