- platform: mqtt
  name: "Jeff Phone Battery"
  state_topic: "owntracks/owntracks/jeffreystonesiphone"
  qos: 0
  unit_of_measurement: "%"
  value_template: '{{ value_json.batt }}'
- platform: mqtt
  name: "Jeff Velocity"
  state_topic: "owntracks/owntracks/jeffreystonesiphone"
  qos: 0
  unit_of_measurement: "kmh"
  value_template: '{{ value_json.vel }} '
#### Life 360:
- platform: mqtt
  name: "Jeff iPhone Battery"
  state_topic: "owntracks/jeffrey/377fadfe-9d7e-410f-b71b-d84c06547c00"
  qos: 0
  unit_of_measurement: "%"
  value_template: '{{ value_json.batt }}'
- platform: mqtt
  name: "Kat iPhone Battery"
  state_topic: "owntracks/kat/2f1c6721-10dd-491e-a7dc-a9833d1c6cf5"
  qos: 0
  unit_of_measurement: "%"
  value_template: '{{ value_json.batt }}'
- platform: mqtt
  state_topic: "owntracks/jeffrey/377fadfe-9d7e-410f-b71b-d84c06547c00" 
  name: "Jeff iPhone Charging"
  value_template: '{{ value_json.charge}}'
- platform: mqtt
  state_topic: "owntracks/kat/2f1c6721-10dd-491e-a7dc-a9833d1c6cf5" 
  name: "Kat iPhone Charging"
  value_template: '{{ value_json.charge}}'
