- platform: template
  sensors:
    garage_door:
      unit_of_measurement: '%'
      value_template: >-
          {%- if states.cover.garage_door }
              {{ states.cover.garage_door }}
          {% else %}
              {{ states.sensor.garage_door.state }}
          {%- endif %}
