- platform: darksky
  api_key: !secret FORCAST_API_KEY
  forecast:
    - 0
  monitored_conditions:
    - summary
    - icon
    - nearest_storm_distance
    - nearest_storm_bearing
    - precip_type
    - precip_intensity
    - precip_probability
    - temperature
    - temperature_high
    - temperature_low
    - apparent_temperature
    - dew_point
    - wind_speed
    - wind_bearing
    - cloud_cover
    - humidity
    - pressure
    - visibility
    - ozone
    - minutely_summary
    - hourly_summary
    - daily_summary
    - precip_intensity_max
  update_interval:
    # At least one of these must be specified:
    days: 0
    hours: 0
    minutes: 5
    seconds: 0
    milliseconds: 0
- platform: pollen
  zip_code: "30017"
  monitored_conditions:
    - allergy_index_today
    - asthma_index_today
## Accurite 158 - Back Porch
- platform: mqtt
  name: "Accurite Back Porch Temperature"
  state_topic: "house/accurite-158/temperature"
- platform: mqtt
  name: "Accurite Back Porch Humidity"
  state_topic: "house/accurite-158/humidity"
# - platform: mqtt
#   name: "Accurite Back Porch Status"
#   state_topic: "house/accurite-158/status"
# - platform: mqtt
#   name: "Accurite Back Porch Battery"
#   state_topic: "house/accurite-158/battery"
- platform: mqtt
  name: "Accurite Back Porch Model"
  state_topic: "house/accurite-158/model"
- platform: mqtt
  name: "Accurite Back Porch lupdate"
  state_topic: "house/accurite-158/lastupdate"
- platform: mqtt
  name: "Accurite Garage Temperature"
  state_topic: "house/accurite-10968/temperature"
- platform: mqtt
  name: "Accurite Garage Humidity"
  state_topic: "house/accurite-10968/humidity"
- platform: mqtt
  name: "Accurite Garage Model"
  state_topic: "house/accurite-10968/model"
- platform: mqtt
  name: "Accurite Garage lupdate"
  state_topic: "house/accurite-10968/lastupdate"

- platform: template
  sensors:
    clothing_forecast:
      friendly_name: "Clothing Forecast"
      unit_of_measurement: ''
      value_template: >-
          {%- if states('sensor.dark_sky_daytime_high_temperature_0')|float > 63 %}
            {%- if states('sensor.dark_sky_daytime_high_temperature_0')|float < 80 %}
              Nice
            {% elif states('sensor.dark_sky_daytime_high_temperature_0')|float > 95 %}
              Hot
            {% else %}
              Toasty
            {%- endif %}
          {% elif states('sensor.dark_sky_daytime_high_temperature_0')|float < 64 %}
            {%- if states('sensor.dark_sky_daytime_high_temperature_0')|float < 32 %}
              Freezing
            {% elif states('sensor.dark_sky_daytime_high_temperature_0')|float > 50 %}
              Chilly
            {% else %}
              Cold
            {%- endif %}
          {% else %}
           Unknown
          {%- endif %}