- platform: mqtt
  name: "Garage Motion" # Dome Motion Sensor
  state_topic: "smartthings/Garage Motion/contact"
  payload_on: "active"
  payload_off: "inactive"
  device_class: motion

- platform: command_line 
  name: vlc player
  command: 'pidof vlc | wc -l'
  payload_on: 1
  payload_off: 0
  scan_interval: 10