trash_pickup:
  name: Trash Pickup
  options:
    - Monday
    - Tuesday
    - Wednesday
    - Thursday
    - Friday
  initial: Tuesday
  icon: mdi:delete-variant 
recycle_pickup:
  name: Recycle Pickup
  options:
    - Monday
    - Tuesday
    - Wednesday
    - Thursday
    - Friday
  initial: Tuesday
  icon: mdi:delete-variant
