alias: "Close Garage if we leave"
trigger:
  - platform: state
    entity_id: group.family
    state: "not home"
condition:
  - condition: state
    entity_id: cover.garage_door
    state: "open"
action:
  - service: notify.notify
    data:
      title: "No one home, Garage Open"
  - service: cover.close_cover
