alias: "Cloudy, inside on if home"
trigger:
  platform: time
  after: '14:00:00'
condition:
  - condition: numeric_state
    entity_id: sensor.dark_sky_cloud_coverage
    above: 90
  - condition: state
    entity_id: group.family
    state: "home"
action:
  - service: notify.notify
    data:
      title: "HA: Turning on Lights - Cloudy"
