alias: "Good Night"
trigger:
  platform: time
  hours: 22
  minutes: 00
  seconds: 00
action:
  - service: scene.turn_on
    entity_id: scene.livingroom_night
  - service: notify.notify
    data:
      title: "HA: Shutting down for the night, Good Night"
