alias: "Good Morning"
trigger:
  platform: time
  hours: 05
  minutes: 15
  seconds: 00
action:
  - service: scene.turn_on
    entity_id: scene.livingroom_normal
  - service: notify.ios_jeffreystonesiphone
    data:
      message: "Good Morning, Anchorage House is up and online."
