alias: "Jeff Arrives At Summit"
trigger:
  platform: zone
  event: enter
  zone: zone.summit
  entity_id: device_tracker.jeffreystonesiphone
action:
  - service: notify.notify
    data:
      title: "Jarvis"
      message: "Jeff is arriving at Summit"
