alias: "Jeff Leaves Summit"
trigger:
  platform: zone
  event: leave
  zone: zone.summit
  entity_id: device_tracker.owntracks_jeffreysphone
action:
  - service: notify.notify
    data:
      title: 'Jeff Left CAI-Summit'
      message: "Jeff left CAI-Summit"
  - service: input_select.select_option
    data:
      entity_id: input_select.jeff_status
      option: moving