alias: 'Jeff Is Stationary'
trigger:
  platform: numeric_state
  entity_id: sensor.jeff_velocity
  below: 2
action:
  - service: input_select.select_option
    data:
      entity_id: input_select.jeff_status
      option: stationary