alias: "Jeff Leaves Home"
trigger:
  platform: zone
  event: leave
  zone: zone.home
  entity_id: device_tracker.jeffreysiphone
action:
  - service: notify.notify
    data:
      title: 'Anchorage House'
      message: "Jeff left home"
  - service: input_select.select_option
    data:
      entity_id: input_select.jeff_status
      option: moving