alias: 'Jeff Is Walking'
trigger:
  platform: numeric_state
  entity_id: sensor.jeff_velocity
  above: 2
  below: 8
condition:
  condition: state
  entity_id: device_tracker.owntracks_jeffreysphone
  state: "not_home"
action:
  - service: input_select.select_option
    data:
      entity_id: input_select.jeff_status
      option: walking