alias: "Jeff Arrives Home"
trigger:
  platform: zone
  event: enter
  zone: zone.home
  entity_id: device_tracker.jeffreystonesiphone
action:
  - service: notify.ios_katherinestonesiphone
    data:
      message: "Jeff is home"
