alias: "Jeff Arrives Home"
trigger:
#  platform: zone
#  event: enter
#  zone: zone.home
#  entity_id: device_tracker.jeffreystonesiphone
  platform: mqtt
  topic: anchoragehouse/jeffrey/status
  # Optional
  payload: 'unknown'
action:
  - service: notify.notify
    data:
      title: "Jarvis"
      message: "Jeff has arrived home"
  - service: script.jeff_unknown
