alias: "Jeff Leaves Summit"
trigger:
  platform: zone
  event: leave
  zone: zone.summit
  entity_id: device_tracker.jeffreystonesiphone
action:
  - service: notify.notify
    data:
      title: "Jarvis"
      message: "Jeff has left summit"
