alias: "Jeff Arrives At Summit"
trigger:
  platform: zone
  event: enter
  zone: zone.summit
  entity_id: device_tracker.jeffreystonesiphone
action:
  - service: notify.notify
    data:
      title: "Jarvis"
      message: "Jeff has arrived at Summit"
  - service: script.jeff_is_stationary
