alias: "Jeff Leaves Home"
trigger:
  platform: zone
  event: leave
  zone: zone.home
  entity_id: device_tracker.jeffreystonesiphone
action:
  - service: notify.notify
    data:
      title: "Jarvis"
      message: "Jeff has left home"
  - service: script.jeff_is_moving
