alias: "Jeff Arrives Home"
trigger:
  platform: zone
  event: enter
  zone: zone.home
  entity_id: device_tracker.owntracks_jeffreysphone
action:
  - service: notify.notify
    data:
      title: 'Jeff is Home'
      message: "Jeff is home!"
  - service: input_select.select_option
    data:
      entity_id: input_select.jeff_status
      option: stationary