alias: "Jeff Leaves Manheim"
trigger:
  platform: zone
  event: leave
  zone: zone.manheim
  entity_id: device_tracker.owntracks_jeffreysphone
action:
  - service: notify.notify
    data:
      title: 'Jeff Left Manheim'
      message: "Jeff left Manheim"
  - service: input_select.select_option
    data:
      entity_id: input_select.jeff_status
      option: moving