alias: "Kat Leaves Home"
trigger:
  platform: zone
  event: leave
  zone: zone.home
  entity_id: device_tracker.katherinestonesiphone
action:
  - service: notify.ios_jeffreystonesiphone
    data:
      message: "Kat left home"
