alias: "Kat Arrives Home"
trigger:
  platform: zone
  event: enter
  zone: zone.home
  entity_id: device_tracker.katherinesiphone
action:
  - service: notify.notify
    data:
      title: "Jarvis"
      message: "Kat has arrived home"
  - service: script.kat_is_stationary
