alias: "Kat Leaves Home"
trigger:
  platform: zone
  event: leave
  zone: zone.home
  entity_id: device_tracker.katherinesiphone
action:
  - service: notify.notify
    data:
      message: "Kat left home"
  - service: script.kat_unknown
