alias: "Kat Arrives Home"
trigger:
  platform: zone
  event: enter
  zone: zone.home
  entity_id: device_tracker.katherinesiphone
action:
  - service: notify.ios_jeffreystonesiphone
    data:
      message: "Kat is arriving home"
