alias: "Sunrise Outside off"
trigger:
  platform: sun
  event: sunrise
action:
  - service: notify.notify
    data:
      title: 'Sun is Up!'
      message: "Turning off Outside Lights."
  - service: script.outside_all_off