alias: test
trigger:
  platform: time
  minutes: 10
  seconds: 00
action:
  service: notify.ios_jeffreystonesiphone
  data:
    message: "Test Alert"
    data:
      message: "Test Alert"
      subtitle: "Just a test"
