alias: test
trigger:
  platform: time
  # Matches every hour at 5 minutes past whole
  minutes: 03
  seconds: 00
action:
  ##service: scene.turn_on
  #entity_id: scene.livingroom_night
  service: notify.ios_jeffreystonesiphone
    data:
      message: "Test Alert"
      data:
        subtitle: "Just a test"
