#
#
# Transit
#
############

- alias: Jeff eta home
  trigger:
  - platform: state
    entity_id: sensor.jeff_destination
    to: Home
  action:
  - service: input_boolean.turn_on
    entity_id: input_boolean.jeff_heading_home

