- platform: mqtt
  name: "Back Door"
  state_topic: "zwave2mqtt/nodeID_28/48/1/0"
  payload_on: "open"
  payload_off: "closed"
  device_class: door
- platform: mqtt
  name: "Garage Door"
  state_topic: "zwave2mqtt/nodeID_16/48/1/0"
  payload_on: "true"
  payload_off: "false"
  device_class: garage_door
- platform: mqtt
  name: "Front Door"
  state_topic: "zwave2mqtt/nodeID_27/48/1/0"
  payload_on: "open"
  payload_off: "closed"
  device_class: door
- platform: mqtt
  name: "Laundry Room Door"
  state_topic: "zwave2mqtt/nodeID_26/48/1/0"
  payload_on: "true"
  payload_off: "false"
  device_class: door
- platform: mqtt
  name: "Attic Door" # Dome Door Sensor
  state_topic: "zwave2mqtt/nodeID_18/48/1/0"
  payload_on: "true"
  payload_off: "false"
  device_class: door
- platform: mqtt
  name: "Side Door" # Dome Door Sensor
  state_topic: "zwave2mqtt/side_door/48/1/0"
  payload_on: "true"
  payload_off: "false"
  device_class: door
- platform: mqtt
  name: "Washer Door"
  state_topic: "zwave2mqtt/washer_door/48/1/0"
  payload_on: "true"
  payload_off: "false"
  device_class: door