###############################################################################
#   @author         :   Jeffrey Stone 
#   @date           :   02/19/2019
#   @package        :   Announcements
#   @description    :   Just Normal Announcements. 
###############################################################################

#script:
  
  # annc_storm_statement:
  #   sequence:
  #   - condition: state
  #     entity_id: input_boolean.vacation_mode
  #     state: 'off'
  #   - service: script.text_notify
  #     data:
  #       message: Severe Storm Statement Issued for Anchorage House
  # annc_tstorm_watch:
  #   sequence:
  #   - condition: state
  #     entity_id: input_boolean.vacation_mode
  #     state: 'off'
  #   - service: script.text_notify
  #     data:
  #       message: Severe Thunderstorm Watch Issued for Anchorage House
  # annc_tstorm_warning:
  #   sequence:
  #   - condition: state
  #     entity_id: input_boolean.vacation_mode
  #     state: 'off'
  #   - service: script.text_notify
  #     data:
  #       message: Severe Thunderstorm Warning Issued for Anchorage House
  # annc_tornado_watch:
  #   sequence:
  #   - condition: state
  #     entity_id: input_boolean.vacation_mode
  #     state: 'off'
  #   - service: script.text_notify
  #     data:
  #       message: Tornado Watch Issued for Anchorage House
  # annc_tornado_warning:
  #   sequence:
  #   - condition: state
  #     entity_id: sensor.family_status
  #     state: Home
  #   - service: script.alert_notify
  #     data_template:
  #       message: "Tornado Warning has been Issued"

automation:
  - id: prebed_routine
    initial_state: true
    alias: Skylar Nightly Announcements
    trigger:
      platform: template
      value_template: "{{ states('sensor.time') == (state_attr('input_datetime.skylar_nightly_report', 'timestamp') | int | timestamp_custom('%H:%M', False)) }}"
    action:
    - service: script.ah_report
      data:
        call_interuption: 1
        call_time_annc: 1
        call_prebed_routine: 1
  
  - id: nightly_report
    initial_state: true
    alias: Nightly Report
    trigger:
      platform: template
      value_template: "{{ states('sensor.time') == (state_attr('input_datetime.nightly_report', 'timestamp') | int | timestamp_custom('%H:%M', False)) }}"
    action:
    - service: script.ah_report
      data:
        call_greeting: 1
        call_evening_greeting: 1
        call_time_annc: 1
        call_weather_alerts: 1
        call_overnight_forecast: 1
        call_upcoming_holidays: 1
        call_reminders: 1
        call_chores: 1

  - id: good_morning_report
    alias: Good Morning Report
    initial_state: true
    trigger:
      platform: template
      value_template: "{{ states('sensor.time') == (state_attr('input_datetime.morning_report', 'timestamp') | int | timestamp_custom('%H:%M', False)) }}"
    action:
    - service: script.ah_report
      data:
        call_greeting: 1
        call_morning_greeting: 1
        call_time_annc: 1
        call_weather_alerts: 1
        call_todays_events: 1
        call_current_conditions_outisde: 1
        call_current_conditions_inside: 1
        call_daily_forecast: 1
        call_upcoming_birthdays: 1
        call_reminders: 1
        call_chores: 1
    - service: script.twitter_notify
      data:
        message: 'I just provided a morning briefing including weather, and traffic
          conditions to the residents of Anchorage House. '
  
  - id: skylar_morning_greeting
    alias: Skylar Morning Greeting
    initial_state: true
    trigger:
      platform: template
      value_template: "{{ states('sensor.time') == (state_attr('input_datetime.skylar_morning_report', 'timestamp') | int | timestamp_custom('%H:%M', False)) }}"
    condition:
    - condition: time
      weekday:
      - mon
      - tue
      - wed
      - thu
      - fri
    action:
    - service: script.ah_report
      data:
        call_interuption: 1
        call_time_annc: 1
        call_skylar_dressed: 1
        call_school_today: 1
        call_skylar_events: 1
        call_clothes_suggestion: 1
  

