###############################################################################
#   @author         :   Jeffrey Stone 
#   @date           :   02/19/2019
#   @package        :   Events
#   @description    :   Special Events.
###############################################################################
automation:
  - id: refresh_special_event_sensors
    alias: Refresh special event sensors
    initial_state: true
    trigger:
    - platform: time
      at: '00:00:01'
    - platform: homeassistant
      event: start
    action:
    - service: python_script.special_events
      data:
        name: Skylar
        type: birthday
        date: 26/02/2014
    - service: python_script.special_events
      data:
        name: Jeff
        type: birthday
        date: 02/09/1975
    - service: python_script.special_events
      data:
        name: Kat
        type: birthday
        date: 18/09/1978
    - service: python_script.special_events
      data:
        name: Our wedding
        type: anniversary
        date: 28/04/2001
    - service: python_script.special_events
      data:
        name: Christmas
        type: holiday
        date: 25/12/2001
    - service: python_script.special_events
      data:
        name: Halloween
        type: holiday
        date: 31/10/2001
    - service: python_script.special_events
      data:
        name: Roadtrip
        type: trip
        date: 30/08/2019
    - service: python_script.special_events
      data:
        name: Disney World
        type: trip
        date: 01/02/2020
    - service: python_script.special_events
      data:
        name: Camping
        type: trip
        date: 09/10/2019